spring:
  application:
    name: healthy_meal_backend
  config:
    import: optional:classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    locations: "classpath:db/migration/mysql"
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://hmb-dev-external-db:3307/test?allowLoadLocalInfile=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}

openai:
  api:
    key: ${OPENAI_KEY}

jwt:
  secret: ${JWT_SECRET}
  token:
    valid_ms: 10800000 # 3시간

storage:
  location: /data

springdoc:
  swagger-ui:
    path: swagger-ui

server:
  port: 5000

logging:
  level:
    root: info
