spring:
  application:
    name: healthy_meal_backend
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  flyway:
    locations: "classpath:db/migration/mysql"
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

storage:
  location: /mnt/vol1/mysql_dir/img/

springdoc:
  swagger-ui:
    path: swagger-ui

server:
  port: 4913

logging:
  level:
    root: info
